{
 "title": "Pi-hole Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PiholeDevices", "query": "2" },
   {
    "name": "JobName",
    "label": "JobName",
    "query": {
     "query": "label_values(pihole_status,job)"
    }
   },
   {
    "name": "Device",
    "query": {
     "query": "query_result(pihole_status{job=~'$JobName'})"
    }
   },
   {
    "name": "QueryTypes",
    "label": "QueryTypes",
    "query": {
     "query": "label_values(pihole_querytypes,type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by () (pihole_status)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Queries",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (pihole_dns_queries_today)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries forwarded",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pihole_queries_forwarded{job=~'$JobName',instance=~'$Device'} + pihole_queries_cached{job=~'$JobName',instance=~'$Device'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries Blocked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pihole_ads_blocked_today{job=~'$JobName',instance=~'$Device'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pihole_domains_being_blocked{hostname=~\"192.168.1.65\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries Answered By",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pihole_forward_destinations{job=~'$JobName',instance=~'$Device'}) by (destination,value)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(pihole_querytypes{job=~'$JobName',instance=~'$Device',type=~'$QueryTypes'}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "% queries blocked",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-\r\nsum by () (\r\n  pihole_ads_percentage_today{hostname=~\"192\\\\.168\\\\.1\\\\.(65|145)\"} \r\n  * pihole_dns_queries_today{hostname=~\"192\\\\.168\\\\.1\\\\.(65|145)\"}\r\n)\r\n/\r\nsum by () (pihole_dns_queries_today{hostname=~\"192\\\\.168\\\\.1\\\\.(65|145)\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries cached/forwarded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (pihole_queries_cached)",
     "legendFormat": "Queries cached"
    },
    {
     "expr": "sum by () (pihole_queries_forwarded)",
     "legendFormat": "Queries forwarded"
    }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (pihole_dns_queries_all_types)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Total Unique Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (pihole_unique_clients)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Client Activity",
   "type": "timeseries",
   "description": "Because this graph does a delta between the current and previous 10 minutes it will take 20 minutes before you start seeing data.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(delta(pihole_top_sources{job=~'$JobName',instance=~'$Device'}[10m]))) by (source)>0",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Top Clients",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(pihole_top_sources{job=~'$JobName',instance=~'$Device'}) by (source)"
    }
   ]
  },
  {
   "title": "Top Permitted Domains",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum(pihole_top_queries{job=~'$JobName',instance=~'$Device'}) by (domain)"
    }
   ]
  },
  {
   "title": "Top Blocked Domains",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "sum(pihole_top_ads{job=~'$JobName',instance=~'$Device'}) by (domain)"
    }
   ]
  }
 ]
}