{
 "title": "Internet Speed",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Download Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_download_bytes*8", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Download Size Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_uploadedbytes_bytes*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_latency_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Download Size Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_downloadedbytes_bytes*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speedtest Results",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 5 },
   "targets": [
    { "expr": "speedtest_download_bytes*8", "legendFormat": "Download" },
    { "expr": "speedtest_upload_bytes*8", "legendFormat": "Speed" }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "speedtest_upload_bytes*8", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Downstream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "speedtest_download_bytes*8", "legendFormat": "Download Speed" }
   ]
  },
  {
   "title": "Upstream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "speedtest_upload_bytes*8", "legendFormat": "Upload Speed" }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "speedtest_jittter_seconds", "legendFormat": "Jitter" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "speedtest_latency_seconds", "legendFormat": "Latency" }
   ]
  }
 ]
}